// src/main/java/com/sflibrary/app/LibraryUsageRecord.java
// This POJO represents a single record from the library usage dataset.

package com.sflibrary.app;

public class LibraryUsageRecord {
    private int recordId; // Auto-generated by DB
    private Integer patronTypeCode;
    private String patronType;
    private Integer circulationActiveYear; // Can be null/empty in CSV
    private String ageRange;
    private Integer totalCheckouts;
    private Integer totalRenewals;
    private String homeLibraryCode;
    private String homeLibraryDefinition;

    // Constructor for loading from CSV (without recordId)
    public LibraryUsageRecord(Integer patronTypeCode, String patronType, Integer circulationActiveYear,
                              String ageRange, Integer totalCheckouts, Integer totalRenewals,
                              String homeLibraryCode, String homeLibraryDefinition) {
        this.patronTypeCode = patronTypeCode;
        this.patronType = patronType;
        this.circulationActiveYear = circulationActiveYear;
        this.ageRange = ageRange;
        this.totalCheckouts = totalCheckouts;
        this.totalRenewals = totalRenewals;
        this.homeLibraryCode = homeLibraryCode;
        this.homeLibraryDefinition = homeLibraryDefinition;
    }

    // Constructor for retrieving from DB (with recordId)
    public LibraryUsageRecord(int recordId, Integer patronTypeCode, String patronType, Integer circulationActiveYear,
                              String ageRange, Integer totalCheckouts, Integer totalRenewals,
                              String homeLibraryCode, String homeLibraryDefinition) {
        this.recordId = recordId;
        this.patronTypeCode = patronTypeCode;
        this.patronType = patronType;
        this.circulationActiveYear = circulationActiveYear;
        this.ageRange = ageRange;
        this.totalCheckouts = totalCheckouts;
        this.totalRenewals = totalRenewals;
        this.homeLibraryCode = homeLibraryCode;
        this.homeLibraryDefinition = homeLibraryDefinition;
    }

    // Getters
    public int getRecordId() { return recordId; }
    public Integer getPatronTypeCode() { return patronTypeCode; }
    public String getPatronType() { return patronType; }
    public Integer getCirculationActiveYear() { return circulationActiveYear; }
    public String getAgeRange() { return ageRange; }
    public Integer getTotalCheckouts() { return totalCheckouts; }
    public Integer getTotalRenewals() { return totalRenewals; }
    public String getHomeLibraryCode() { return homeLibraryCode; }
    public String getHomeLibraryDefinition() { return homeLibraryDefinition; }

    // Setters (useful for setting auto-generated ID after insert)
    public void setRecordId(int recordId) { this.recordId = recordId; }
    public void setPatronTypeCode(Integer patronTypeCode) { this.patronTypeCode = patronTypeCode; }
    public void setPatronType(String patronType) { this.patronType = patronType; }
    public void setCirculationActiveYear(Integer circulationActiveYear) { this.circulationActiveYear = circulationActiveYear; }
    public void setAgeRange(String ageRange) { this.ageRange = ageRange; }
    public void setTotalCheckouts(Integer totalCheckouts) { this.totalCheckouts = totalCheckouts; }
    public void setTotalRenewals(Integer totalRenewals) { this.totalRenewals = totalRenewals; }
    public void setHomeLibraryCode(String homeLibraryCode) { this.homeLibraryCode = homeLibraryCode; }
    public void setHomeLibraryDefinition(String homeLibraryDefinition) { this.homeLibraryDefinition = homeLibraryDefinition; }


    @Override
    public String toString() {
        return "RecordID: " + recordId +
                ", TypeCode: " + patronTypeCode +
                ", Type: '" + patronType + '\'' +
                ", ActiveYear: " + circulationActiveYear +
                ", Age: '" + ageRange + '\'' +
                ", Checkouts: " + totalCheckouts +
                ", Renewals: " + totalRenewals +
                ", LibCode: '" + homeLibraryCode + '\'' +
                ", LibDef: '" + homeLibraryDefinition + '\'';
    }
}
